### ISSUE TITLE
Include setting to allow CORS

### ISSUE THREAD

**Issue by mantagen** [coStars/gothenticate#21]
CORS: cross origin resource sharing
This means, that because I am creating the front end for your app, the requests will be coming from a different URL to your app. The backend is on http://localhost:8000 (_or something_), and frontend will be on http://localhost:1212
By default, hapi doesn't allow CORS, but you can whitelist URLs like I've shown in the image below 

:)

![image](https://cloud.githubusercontent.com/assets/12934669/24224469/fb6aba4c-0f63-11e7-8c2d-b3288a815bcd.png)

**Comment by Alaa-Khattab** [comment]
we did it , thank you :)
