### ISSUE TITLE
Reply with the right status codes!

### ISSUE THREAD

**Issue by mantagen** [coStars/gothenticate#22]
By default, Hapi will reply with 200, meaning that everything is okay.

But if there was a problem, make sure to reply with the right status code!! 

http://www.restapitutorial.com/httpstatuscodes.html

eg: 

![image](https://cloud.githubusercontent.com/assets/12934669/24226037/ca085dc0-0f6c-11e7-95a1-27371a715ecd.png)

**Comment by mantagen** [comment]
for future reference: 

https://github.com/hapijs/boom

;)

**Comment by Alaa-Khattab** [comment]
we did it , thanks :)
